# Generated by Django 5.2 on 2026-05-02 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('image_w', models.PositiveIntegerField(default=0)),
                ('image_h', models.PositiveIntegerField(default=0)),
                ('layout_blocks', models.JSONField(default=list)),
                ('ocr_blocks', models.JSONField(default=list)),
                ('status', models.CharField(default='idle', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='extractor.document')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
