# Generated by Django 5.2 on 2026-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_tag_document_deleted_at_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='structure_status',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='structured_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
