# Generated by Django 5.2.13 on 2026-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_documentpage_structure_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='placed_images',
            field=models.JSONField(default=list),
        ),
    ]
